const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require(process.env.TYPESCRIPT_PATH || '/Applications/DevEco-Studio.app/Contents/tools/ohpm/node_modules/typescript');
const flush = () => new Promise(resolve => setImmediate(resolve));
const source = name => ts.transpileModule(fs.readFileSync(__dirname + '/../system-actions-native/src/main/ets/' + name + '.ets', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
let resolveWindow, delayed = false, failRestore = false;
const target = { keep: false, getWindowProperties() { return { isPrivacyMode: false, isKeepScreenOn: this.keep }; }, async setWindowPrivacyMode() { assert.fail("keep-screen-only does not require PRIVACY_WINDOW"); }, async setWindowKeepScreenOn(value) { if (!value && failRestore) { failRestore = false; throw Error("restore unavailable"); } this.keep = value; } };
const kits = { window: { getLastWindow: () => delayed ? new Promise(resolve => { resolveWindow = resolve; }) : Promise.resolve(target) } };
const policy = {}, observations = {}, modules = {};
vm.runInNewContext(source('WindowPolicy'), { exports: policy, require: () => kits });
vm.runInNewContext(source('SystemObservations'), { exports: observations, require: () => kits });
vm.runInNewContext(source('GycSystemActionsModule'), { exports: modules, require: name => name === './WindowPolicy' ? policy : name === './SystemObservations' ? observations : name === '@kuikly-open/render' ? { KuiklyRenderBaseModule: class { constructor() { this.controller = { getUIAbilityContext: () => ({}) }; } onDestroy() {} } } : kits });
(async () => {
  const replies = [], module = new modules.GycSystemActionsModule({});
  const invoke = (method, id, value) => module.call(method, JSON.stringify({ requestId: id, value }), result => replies.push(result.status));
  invoke('setKeepScreenOn', 'first', 'true'); await flush(); assert.equal(target.keep, true); assert.deepEqual(replies, ['requested']);
  invoke('setKeepScreenOn', 'invalid', 'anything'); await flush(); assert.equal(replies.at(-1), 'invalid_input'); assert.equal(target.keep, true);
  invoke('setKeepScreenOn', 'off', 'false'); await flush(); assert.equal(target.keep, false);
  invoke('setKeepScreenOn', 'retry-owner', 'true'); await flush();
  failRestore = true;
  invoke('setKeepScreenOn', 'restore-failed', 'false'); await flush();
  assert.equal(replies.at(-1), 'unavailable'); assert.equal(target.keep, true);
  invoke('setKeepScreenOn', 'restore-retry', 'false'); await flush();
  assert.equal(replies.at(-1), 'requested'); assert.equal(target.keep, false, 'retry false restores after first platform failure');
  delayed = true;
  invoke('setKeepScreenOn', 'old', 'true'); await flush();
  const oldWindow = resolveWindow;
  invoke('cancel', 'old'); invoke('setKeepScreenOn', 'next', 'true');
  oldWindow(target); await flush();
  resolveWindow(target); await flush(); assert.equal(target.keep, true, 'cancelled old owner cannot release newer owner');
  module.onDestroy(); await flush(); assert.equal(target.keep, false);
  const late = new modules.GycSystemActionsModule({});
  late.call('setKeepScreenOn', JSON.stringify({ requestId: 'late', value: 'true' }), () => assert.fail('destroyed module delivered'));
  await flush(); late.onDestroy(); resolveWindow(target); await flush(); assert.equal(target.keep, false, 'destroy during getLastWindow cannot acquire');
  console.log('OHOS keep screen bridge checks passed: await, malformed input, release, old cancellation, new owner, restore retry and destroy before late Window.');
})().catch(error => { console.error(error); process.exitCode = 1; });
